version: '3.7'
services:
  web:
    build: web
    restart: always
    ports:
      - 5000:5000
    environment: 
      - DEBUG=1
    networks:
      - flask_psql
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_psql
  
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=adverts
    networks:
      - flask_psql
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/web/seed.py

networks:
  flask_psql:
volumes:
  postgres_data:
  